# -*- coding: utf-8 -*-
"""test_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KbiCy4DILja3dMHlrrYd3eYzeYS76_-q
"""

import pytest

import re
import nltk 
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

stop_words = stopwords.words('english')
stemmer = SnowballStemmer('english')

text_cleaning_re = r'\n@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+\n'


def preprocess(text, stem=False):
  text = re.sub(text_cleaning_re, ' ', str(text).lower()).strip()
  tokens = []
  for token in text.split():
    if token not in stop_words:
      if stem:
        tokens.append(stemmer.stem(token))
      else:
        tokens.append(token)
  return " ".join(tokens)

def test_preprocess():
  my_pre = preprocess("traveler",True)
  expected_pre = 'travel'
  assert my_pre == expected_pre
