# -*- coding: utf-8 -*-
"""test_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JVq_QLIAFZgkFs1-o8HIH3VfIp7h0bwV
"""

import pytest


def decode_sentiment(score):
    return "Positive" if score>0.5 else "Negative"

@pytest.mark.parametrize("score,expected_decode", [
    (3, "Positive"),
    (0.1,"Negative"),
    (8, "Negative"),
])

def test_decode_sentiment(score, expected_decode):
  assert decode_sentiment(score) == expected_decode